# Generated by Django 2.1.15 on 2020-05-25 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtail_localize_translation', '0001_initial_squashed_0004_change_language_to_locale_3'),
        ('wagtail_localize', '0006_delete_language_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtail_localize_workflow', '0004_remove_translation_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wagtaillocalize_translation_requests_created', to=settings.AUTH_USER_MODEL)),
                ('sources', models.ManyToManyField(to='wagtail_localize_translation.TranslationSource')),
                ('source_locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale')),
                ('target_locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale')),
            ],
        ),
    ]
