# Generated by Django 2.2.4 on 2019-08-14 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("wagtail_localize_translation_memory", "0002_pagelocation_order")]

    operations = [
        migrations.AddField(
            model_name="segmenttranslation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="segmenttranslation",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
