# Generated by Django 2.2.9 on 2020-01-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_translation_memory", "0008_migrate_to_translation_app"),
    ]

    operations = [
        migrations.RemoveField(model_name="segmentpagelocation", name="page_revision",),
        migrations.RemoveField(model_name="segmentpagelocation", name="segment",),
        migrations.AlterUniqueTogether(
            name="segmenttranslation", unique_together=None,
        ),
        migrations.RemoveField(model_name="segmenttranslation", name="language",),
        migrations.RemoveField(model_name="segmenttranslation", name="translation_of",),
        migrations.RemoveField(
            model_name="templatepagelocation", name="page_revision",
        ),
        migrations.RemoveField(model_name="templatepagelocation", name="template",),
        migrations.DeleteModel(name="Segment",),
        migrations.DeleteModel(name="SegmentPageLocation",),
        migrations.DeleteModel(name="SegmentTranslation",),
        migrations.DeleteModel(name="Template",),
        migrations.DeleteModel(name="TemplatePageLocation",),
    ]
