# Generated by Django 2.1.7 on 2019-03-25 16:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail_localize.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0002_region'),
        ('wagtail_localize_sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelanguage',
            name='region',
            field=models.ForeignKey(default=wagtail_localize.models.Region.default_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtail_localize.Region', verbose_name='region'),
        ),
    ]
