# Generated by Django 2.1.10 on 2019-08-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("wagtail_localize_workflow", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="translationrequest",
            name="source_locale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtail_localize.Locale",
            ),
        ),
        migrations.AlterField(
            model_name="translationrequest",
            name="target_locale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtail_localize.Locale",
            ),
        ),
        migrations.AlterField(
            model_name="translationrequest",
            name="target_root",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
        migrations.AlterField(
            model_name="translationrequestpage",
            name="source_revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.PageRevision",
            ),
        ),
    ]
