# Generated by Django 2.1.7 on 2019-03-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtail_localize', '0009_region_is_active'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HTMLTemplatePageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('html_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_locations', to='wagtail_localize_translation_memory.HTMLTemplate')),
                ('page_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.PageRevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HTMLTemplateSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('html_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='wagtail_localize_translation_memory.HTMLTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('text', models.TextField()),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtail_localize.Locale')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentPageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('page_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.PageRevision')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_locations', to='wagtail_localize_translation_memory.Segment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtail_localize.Locale')),
                ('translation_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='wagtail_localize_translation_memory.Segment')),
            ],
        ),
        migrations.AddField(
            model_name='htmltemplatesegment',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize_translation_memory.Segment'),
        ),
        migrations.AlterUniqueTogether(
            name='segmenttranslation',
            unique_together={('locale', 'translation_of')},
        ),
    ]
