# Generated by Django 6.1 on 2026-08-19 13:58

import uuid

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blogpage_body"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpersonrelationship",
            name="locale",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpersonrelationship",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="person",
            name="locale",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="blogpersonrelationship",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AlterUniqueTogether(
            name="person",
            unique_together={("translation_key", "locale")},
        ),
    ]
