# Generated by Django 2.2.9 on 2020-01-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize", "0002_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locale",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locales",
                to="wagtail_localize.Language",
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(name="locale", unique_together=set(),),
        migrations.RemoveField(model_name="locale", name="region",),
        migrations.AlterModelOptions(
            name='locale',
            options={'ordering': ['-is_active', 'language__code']},
        ),
        migrations.DeleteModel(name="Region",),
    ]
