# Generated by Django 2.2.9 on 2020-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize", "0003_delete_region_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="locale",
            name="language_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
