# Generated by Django 2.1.7 on 2019-03-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0003_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='wagtail_localize.Language')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='wagtail_localize.Region')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='locale',
            unique_together={('region', 'language')},
        ),
    ]
