# Generated by Django 2.2.9 on 2020-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize", "0005_populate_locale_language_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locale", options={"ordering": ["-is_active", "language_code"]},
        ),
        migrations.RemoveField(model_name="locale", name="language",),
        migrations.AlterField(
            model_name="locale",
            name="language_code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(name="Language",),
    ]
