# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0005_language_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
