# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 16:36
from __future__ import unicode_literals

from django.db import migrations


def set_region_is_default(apps, schema_editor):
    Region = apps.get_model('wagtail_localize.Region')
    Region.objects.filter(slug='default').update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0006_region_is_default'),
    ]

    operations = [
        migrations.RunPython(set_region_is_default, migrations.RunPython.noop)
    ]
