# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0007_set_region_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['-is_default', 'name']},
        ),
    ]
