# Generated by Django 2.1.7 on 2019-03-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0008_region_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['-is_active', '-is_default', 'name']},
        ),
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
