# Generated by Django 3.1.1 on 2020-09-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0058_page_alias_of'),
        ('wagtail_localize', '0009_stringtranslation_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocaleSynchronization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.locale')),
                ('sync_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.locale')),
            ],
        ),
    ]
