# Generated by Django 3.1 on 2020-09-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0057_page_locale_fields_notnull'),
        ('wagtail_localize', '0010_overridablesegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to='wagtail_localize.translationcontext')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='wagtailcore.locale')),
            ],
        ),
    ]
