# Generated by Django 3.1.2 on 2020-10-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0011_segmentoverride'),
        ('wagtail_localize', '0010_localesynchronisation'),
    ]

    operations = [
    ]
