# Generated by Django 3.1.3 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_localize", "0016_rename_page_revision_translationlog_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="localesynchronization",
            name="sync_page_status",
            field=models.CharField(
                choices=[("MIRROR", "Mirror source status"), ("DRAFT", "Draft (always unpublished)")],
                default="MIRROR",
                help_text="Choose how synced pages should be published. 'Draft' keeps all synced pages unpublished until manually reviewed. 'Mirror' matches the source page's live/draft status.",
                max_length=10,
                verbose_name="Page status for synced pages",
            ),
        ),
    ]
