# Generated by Django 6.0.3 on 2026-04-06 21:34

import wagtail.fields

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_body_homepage_featured_section_3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("package_callout", 2),
                    ("heading_block", 5),
                    ("paragraph_block", 6),
                    ("image_block", 9),
                    ("block_quote", 15),
                    ("embed_block", 16),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a header size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 3), ("size", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "description": "A rich text paragraph",
                            "icon": "pilcrow",
                            "preview_value": '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ',
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 7), ("caption", 8), ("attribution", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.TextBlock", (), {}),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "label": "e.g. Mary Berry", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                            ],
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("large", "Large")],
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("theme", 12), ("text_size", 13)]],
                        {"collapsed": True},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 10), ("attribute_name", 11), ("settings", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "description": "An embedded video or other media",
                            "help_text": "Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            "icon": "media",
                            "preview_template": "base/preview/static_embed_block.html",
                            "preview_value": "https://www.youtube.com/watch?v=mwrGSfiB1Mg",
                            "template": "blocks/embed_block.html",
                        },
                    ),
                },
                verbose_name="Home content block",
            ),
        ),
    ]
