# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtail_i18n', '0005_language_is_active'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_requests_created', to=settings.AUTH_USER_MODEL)),
                ('source_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtail_i18n.Locale')),
                ('target_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtail_i18n.Locale')),
                ('target_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationRequestPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_pages', to='wagtail_i18n_workflow.TranslationRequestPage')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wagtail_i18n_workflow.TranslationRequest')),
                ('source_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.PageRevision')),
            ],
        ),
    ]
