# Generated by Django 6.1 on 2026-08-18 12:22

import uuid

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basepage", "0002_basepage_locale"),
        ("wagtailcore", "0098_apitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepage",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AddField(
            model_name="basepage",
            name="latest_revision_created_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="latest revision created at"
            ),
        ),
        migrations.AddField(
            model_name="basepage",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="live revision",
            ),
        ),
        migrations.AlterField(
            model_name="basepage",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="basepage",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="basepage",
            unique_together={("translation_key", "locale")},
        ),
    ]
