# Generated by Django 2.2.9 on 2020-01-28 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize", "0002_initial_data"),
        ("wagtail_localize_translation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="locale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtail_localize.Locale",
            ),
        ),
        migrations.AddField(
            model_name="segmenttranslation",
            name="locale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtail_localize.Locale",
            ),
        ),
    ]
