# Generated by Django 3.0.6 on 2020-05-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('wagtail_localize_translation', '0002_rename_translationcontext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TranslatableRevision',
            new_name='TranslationSource',
        ),
        migrations.RenameField(
            model_name='translationlog',
            old_name='revision',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='relatedobjectlocation',
            old_name='revision',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='segmentlocation',
            old_name='revision',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='templatelocation',
            old_name='revision',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='translationsource',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='wagtail_localize_translation.TranslatableObject'),
        ),
    ]
