# Generated by Django 3.0.6 on 2020-07-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0006_delete_language_model'),
        ('wagtail_localize_translation', '0003_rename_translationsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenttranslation',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_translations', to='wagtail_localize.Locale'),
        ),
    ]
