# Generated by Django 3.0.6 on 2020-06-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0007_translatableobject'),
        ('wagtail_localize_translation', '0003_rename_translationsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedobjectlocation',
            name='core_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_localize.TranslatableObject'),
        ),
        migrations.AddField(
            model_name='translationcontext',
            name='core_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_localize.TranslatableObject'),
        ),
        migrations.AddField(
            model_name='translationsource',
            name='core_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_localize.TranslatableObject'),
        ),
    ]
