# Generated by Django 3.0.6 on 2020-06-24 19:50

from django.db import migrations


def migrate_forwards(apps, schema_editor):
    NewTranslatableObject = apps.get_model('wagtail_localize.TranslatableObject')

    TranslationSource = apps.get_model('wagtail_localize_translation.TranslationSource')
    for source in TranslationSource.objects.only('id', 'object').select_related('object'):
        source.core_object, created = NewTranslatableObject.objects.get_or_create(
            legacy_translation_key=source.object_id,
            content_type_id=source.object.content_type_id
        )
        source.save(update_fields=['core_object'])

    TranslationContext = apps.get_model('wagtail_localize_translation.TranslationContext')
    for context in TranslationContext.objects.only('id', 'object').select_related('object'):
        context.core_object , created = NewTranslatableObject.objects.get_or_create(
            legacy_translation_key=context.object_id,
            content_type_id=context.object.content_type_id
        )
        context.save(update_fields=['core_object'])

    RelatedObjectLocation = apps.get_model('wagtail_localize_translation.RelatedObjectLocation')
    for location in RelatedObjectLocation.objects.only('id', 'object').select_related('object'):
        location.core_object, created = NewTranslatableObject.objects.get_or_create(
            legacy_translation_key=location.object_id,
            content_type_id=location.object.content_type_id
        )
        location.save(update_fields=['core_object'])


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0004_core_translatable_object'),
    ]

    operations = [
        migrations.RunPython(migrate_forwards),
    ]
