# Generated by Django 2.1.15 on 2020-06-30 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0006_delete_language_model'),
        ('wagtail_localize_translation', '0005_auto_20200627_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='wagtail_localize_translation.TranslationSource')),
                ('target_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='wagtail_localize.Locale')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='translationrequest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='translationrequest',
            name='source',
        ),
        migrations.RemoveField(
            model_name='translationrequest',
            name='target_locale',
        ),
        migrations.AlterField(
            model_name='segmenttranslation',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_translations', to='wagtail_localize.Locale'),
        ),
        migrations.DeleteModel(
            name='TranslationRequest',
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('source', 'target_locale')},
        ),
    ]
