# Generated by Django 3.0.6 on 2020-06-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0005_migrate_to_core_translatable_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedobjectlocation',
            name='object',
        ),
        migrations.RemoveField(
            model_name='translationsource',
            name='object',
        ),
        migrations.AlterUniqueTogether(
            name='translationcontext',
            unique_together={('core_object', 'path_id')},
        ),
        migrations.DeleteModel(
            name='TranslatableObject',
        ),
        migrations.RemoveField(
            model_name='translationcontext',
            name='object',
        ),
    ]
