# Generated by Django 2.2.9 on 2019-12-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("wagtail_localize", "0002_initial_data"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtail_localize_translation_memory", "0006_segmentpagelocation_html_attrs"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslatableObject",
            fields=[
                (
                    "translation_key",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={"unique_together": {("content_type", "translation_key")},},
        ),
        migrations.CreateModel(
            name="TranslatableRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_json", models.TextField()),
                ("created_at", models.DateTimeField()),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtail_localize.Locale",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="wagtail_localize_translation_memory.TranslatableObject",
                    ),
                ),
                (
                    "page_revision",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wagtaillocalize_revision",
                        to="wagtailcore.PageRevision",
                    ),
                ),
            ],
        ),
    ]
