# Generated by Django 3.0.6 on 2020-06-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0006_delete_translatable_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedobjectlocation',
            name='core_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='wagtail_localize.TranslatableObject'),
        ),
        migrations.AlterField(
            model_name='translationcontext',
            name='core_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='wagtail_localize.TranslatableObject'),
        ),
        migrations.AlterField(
            model_name='translationsource',
            name='core_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='wagtail_localize.TranslatableObject'),
        ),
        migrations.RenameField(
            model_name='relatedobjectlocation',
            old_name='core_object',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='translationcontext',
            old_name='core_object',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='translationsource',
            old_name='core_object',
            new_name='object',
        ),
        migrations.AlterUniqueTogether(
            name='translationcontext',
            unique_together={('object', 'path_id')},
        ),
    ]
