# Generated by Django 2.1.15 on 2020-06-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0006_rename_translationrequest_to_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='wagtail_localize_translation.TranslatableObject'),
        ),
    ]
