# Generated by Django 2.1.15 on 2020-06-30 15:23

from django.db import migrations


def populate_translation_object(apps, schema_editor):
    Translation = apps.get_model('wagtail_localize_translation.Translation')
    for translation in Translation.objects.all().select_related('source'):
        translation.object_id = translation.source.object_id
        translation.save(update_fields=['object_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0007_translation_object'),
    ]

    operations = [
        migrations.RunPython(populate_translation_object, migrations.RunPython.noop),
    ]
