# Generated by Django 3.0.6 on 2020-06-24 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtail_localize_translation', '0007_rename_new_object_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationsource',
            name='specific_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
    ]
