# Generated by Django 3.0.6 on 2020-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0008_translationsource_specific_content_type_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationsource',
            name='object_repr',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
