# Generated by Django 2.1.15 on 2020-06-30 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0006_delete_language_model'),
        ('wagtail_localize_translation', '0008_populate_translation_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='wagtail_localize_translation.TranslatableObject'),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('object', 'target_locale')},
        ),
    ]
