# Generated by Django 2.1.15 on 2020-07-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0009_translation_object_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatableobject',
            name='path',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='translationsource',
            name='object_title',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
