# Generated by Django 3.0.6 on 2020-07-17 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('wagtail_localize', '0006_delete_language_model'),
        ('wagtail_localize_translation', '0009_translationsource_object_repr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Segment',
            new_name='String',
        ),
        migrations.RenameField(
            model_name='string',
            old_name='text',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='string',
            old_name='text_id',
            new_name='data_hash',
        ),
        migrations.AlterField(
            model_name='string',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_strings', to='wagtail_localize.Locale'),
        ),
        migrations.AlterUniqueTogether(
            name='string',
            unique_together={('locale', 'data_hash')},
        ),

        migrations.RenameModel(
            old_name='SegmentLocation',
            new_name='StringLocation',
        ),
        migrations.RenameField(
            model_name='stringlocation',
            old_name='html_attrs',
            new_name='attrs',
        ),
        migrations.RenameField(
            model_name='stringlocation',
            old_name='segment',
            new_name='string',
        ),

        migrations.RenameField(
            model_name='template',
            old_name='segment_count',
            new_name='string_count',
        ),
    ]
