# Generated by Django 2.1.15 on 2020-07-02 08:53

from django.db import migrations
from django.db.models import Value as V, F
from django.db.models.functions import Concat


def populate_object_path(apps, schema_editor):
    TranslatableObject = apps.get_model('wagtail_localize_translation.TranslatableObject')
    TranslatableObject.objects.update(path=Concat(V('migrated/'), F('translation_key')))


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0010_object_title_and_path copy'),
    ]

    operations = [
        migrations.RunPython(populate_object_path, migrations.RunPython.noop),
    ]
