# Generated by Django 2.1.15 on 2020-07-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0011_populate_object_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatableobject',
            name='path',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
