# Generated by Django 3.0.6 on 2020-07-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('wagtail_localize_translation', '0011_rename_segmenttranslation_to_translatedstring'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedObjectLocation',
            new_name='RelatedObjectSegment',
        ),
        migrations.RenameModel(
            old_name='StringLocation',
            new_name='StringSegment',
        ),
        migrations.RenameModel(
            old_name='TemplateLocation',
            new_name='TemplateSegment',
        ),
        migrations.AlterField(
            model_name='stringsegment',
            name='string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='wagtail_localize_translation.String'),
        ),
        migrations.AlterField(
            model_name='templatesegment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='wagtail_localize_translation.Template'),
        ),
    ]
