# Generated by Django 2.1.15 on 2020-07-03 11:13

from django.db import migrations


def populate_translationsource_specific_content_type(apps, schema_editor):
    TranslationSource = apps.get_model('wagtail_localize_translation.TranslationSource')

    for source in TranslationSource.objects.all().select_related('object').iterator():
        source.specific_content_type_id = source.object.content_type_id
        source.save(update_fields=['specific_content_type_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0013_translationsource_specific_content_type'),
    ]

    operations = [
        migrations.RunPython(populate_translationsource_specific_content_type, migrations.RunPython.noop),
    ]
