# Generated by Django 2.1.15 on 2020-07-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0014_populate_translationsource_specific_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationsource',
            name='specific_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
    ]
