# Generated by Django 2.2.9 on 2020-01-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_translation_memory", "0015_remove_location_paths"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="translationlog", unique_together=set(),),
    ]
