# Generated by Django 2.1.15 on 2020-07-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0015_translationsource_specific_content_type_notnull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationsource',
            name='page_revision',
        ),
    ]
