# Generated by Django 2.1.15 on 2020-07-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize_translation', '0016_remove_translationsource_page_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatableobject',
            name='path',
        ),
    ]
