# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 20:08
from __future__ import unicode_literals

from django.db import migrations
import wagtail_translation.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_translation', '0010_language_and_locale_ordering'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='language',
            managers=[
                ('objects', wagtail_translation.models.LanguageManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='locale',
            managers=[
                ('objects', wagtail_translation.models.LocaleManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='region',
            managers=[
                ('objects', wagtail_translation.models.RegionManager()),
            ],
        ),
    ]
