# Generated by Django 2.1.10 on 2019-08-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural")
    ]

    operations = [
        migrations.CreateModel(
            name="PontoonResource",
            fields=[
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                (
                    "current_revision",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.PageRevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PontoonResourceSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pushed_at", models.DateTimeField(null=True)),
                ("pushed_commit_sha", models.CharField(blank=True, max_length=40)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="wagtail_localize_pontoon.PontoonResource",
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontoon_submission",
                        to="wagtailcore.PageRevision",
                    ),
                ),
            ],
        ),
    ]
