# Generated by Django 2.2.5 on 2019-09-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wagtail_localize_pontoon", "0004_pontoonsynclogresource")]

    operations = [
        migrations.AlterField(
            model_name="pontoonsynclog",
            name="commit_id",
            field=models.CharField(blank=True, max_length=40),
        )
    ]
