# Generated by Django 2.2.6 on 2019-10-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wagtail_localize_pontoon", "0005_auto_20190923_1405")]

    operations = [
        migrations.AlterUniqueTogether(
            name="pontoonresourcetranslation", unique_together=set()
        )
    ]
