# Generated by Django 2.2.9 on 2019-12-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_pontoon", "0006_auto_20191007_1700"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pontoonresource",
            old_name="current_revision",
            new_name="current_page_revision",
        ),
        migrations.RenameField(
            model_name="pontoonresourcesubmission",
            old_name="revision",
            new_name="page_revision",
        ),
        migrations.RenameField(
            model_name="pontoonresourcetranslation",
            old_name="revision",
            new_name="page_revision",
        ),
    ]
