# Generated by Django 2.2.9 on 2019-12-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_translation_memory", "0009_migrate_to_new_location_models"),
        ("wagtail_localize_pontoon", "0007_rename_revision_to_page_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoonresource",
            name="current_revision",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtail_localize_translation_memory.TranslatableRevision",
            ),
        ),
        migrations.AddField(
            model_name="pontoonresource",
            name="object",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtail_localize_translation_memory.TranslatableObject",
            ),
        ),
        migrations.AddField(
            model_name="pontoonresourcesubmission",
            name="revision",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pontoon_submission",
                to="wagtail_localize_translation_memory.TranslatableRevision",
            ),
        ),
    ]
