# Generated by Django 2.2.7 on 2019-12-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_pontoon", "0009_populate_new_revision_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pontoonresource", name="current_page_revision",
        ),
        migrations.AlterField(
            model_name="pontoonresource",
            name="object",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtail_localize_translation_memory.TranslatableObject",
            ),
        ),
        migrations.RemoveField(
            model_name="pontoonresourcesubmission", name="page_revision",
        ),
        migrations.AlterField(
            model_name="pontoonresourcesubmission",
            name="revision",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pontoon_submission",
                to="wagtail_localize_translation_memory.TranslatableRevision",
            ),
        ),
        migrations.RemoveField(
            model_name="pontoonresourcetranslation", name="page_revision",
        ),
    ]
