# Generated by Django 2.2.9 on 2019-12-18 18:47

from django.db import migrations


def populate_new_resource_model(apps, schema_editor):
    OldResource = apps.get_model("wagtail_localize_pontoon.OldPontoonResource")
    NewResource = apps.get_model("wagtail_localize_pontoon.NewPontoonResource")
    SyncLogResource = apps.get_model("wagtail_localize_pontoon.PontoonSyncLogResource")
    ResourceSubmission = apps.get_model(
        "wagtail_localize_pontoon.PontoonResourceSubmission"
    )

    # Create new resources
    id_mapping = {}
    for resource in OldResource.objects.iterator():
        id_mapping[resource.page_id] = resource.object_id

        NewResource.objects.create(
            object_id=resource.object_id,
            path=resource.path,
            current_revision_id=resource.current_revision_id,
        )

    # Populate new foreign key fields
    for page_id, object_id in id_mapping.items():
        SyncLogResource.objects.filter(old_resource_id=page_id).update(
            new_resource_id=object_id
        )
        ResourceSubmission.objects.filter(old_resource_id=page_id).update(
            new_resource_id=object_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_pontoon", "0011_replace_pontoonresource"),
    ]

    operations = [
        migrations.RunPython(populate_new_resource_model),
    ]
