# Generated by Django 2.2.9 on 2019-12-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_pontoon", "0012_populate_new_resource_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pontoonresourcesubmission", name="old_resource",
        ),
        migrations.RemoveField(
            model_name="pontoonsynclogresource", name="old_resource",
        ),
        migrations.AlterField(
            model_name="pontoonresourcesubmission",
            name="new_resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="wagtail_localize_pontoon.NewPontoonResource",
            ),
        ),
        migrations.AlterField(
            model_name="pontoonsynclogresource",
            name="new_resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="wagtail_localize_pontoon.NewPontoonResource",
            ),
        ),
        migrations.DeleteModel(name="OldPontoonResource",),
        # Must be after deleting OldPontoonResource to prevent name clashes with
        # previous indexes. Django sometimes doesn't rename them.
        migrations.RenameModel(
            old_name="NewPontoonResource", new_name="PontoonResource",
        ),
        migrations.RenameField(
            model_name="pontoonresourcesubmission",
            old_name="new_resource",
            new_name="resource",
        ),
        migrations.RenameField(
            model_name="pontoonsynclogresource",
            old_name="new_resource",
            new_name="resource",
        ),
    ]
