# Generated by Django 2.2.6 on 2019-11-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wagtail_localize_translation_memory",
            "0005_segmenttranslation_updated_at_autofill",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="segmentpagelocation",
            name="html_attrs",
            field=models.TextField(blank=True),
        )
    ]
