# Generated by Django 2.2.7 on 2019-12-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_translation_memory", "0009_migrate_to_new_location_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatepagelocation", name="page_revision",
        ),
        migrations.RemoveField(model_name="templatepagelocation", name="template",),
        migrations.DeleteModel(name="SegmentPageLocation",),
        migrations.DeleteModel(name="TemplatePageLocation",),
    ]
