# Generated by Django 2.2.7 on 2020-01-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "wagtail_localize_translation_memory",
            "0013_populate_segmenttranslationcontext",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="relatedobjectlocation", name="path",),
        migrations.RemoveField(model_name="segmentlocation", name="path",),
        migrations.RemoveField(model_name="templatelocation", name="path",),
        migrations.AlterField(
            model_name="relatedobjectlocation",
            name="context",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="wagtail_localize_translation_memory.SegmentTranslationContext",
            ),
        ),
        migrations.AlterField(
            model_name="segmentlocation",
            name="context",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="wagtail_localize_translation_memory.SegmentTranslationContext",
            ),
        ),
        migrations.AlterField(
            model_name="templatelocation",
            name="context",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="wagtail_localize_translation_memory.SegmentTranslationContext",
            ),
        ),
    ]
