# Generated by Django 2.1.7 on 2019-03-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtail_i18n_translation_memory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HTMLTemplate',
            new_name='Template',
        ),
        migrations.RenameModel(
            old_name='HTMLTemplatePageLocation',
            new_name='TemplatePageLocation',
        ),
        migrations.RenameModel(
            old_name='HTMLTemplateSegment',
            new_name='TemplateSegment',
        ),
        migrations.RenameField(
            model_name='templatepagelocation',
            old_name='html_template',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='templatesegment',
            old_name='html_template',
            new_name='template',
        ),
        migrations.AddField(
            model_name='template',
            name='template_format',
            field=models.CharField(default='html', max_length=100),
            preserve_default=False,
        ),
    ]
