# Generated by Django 2.1.7 on 2019-03-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n_translation_memory', '0002_template_formats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatepagelocation',
            name='page_revision',
        ),
        migrations.RemoveField(
            model_name='templatepagelocation',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templatesegment',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='templatesegment',
            name='template',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='TemplatePageLocation',
        ),
        migrations.DeleteModel(
            name='TemplateSegment',
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('template', models.TextField()),
                ('template_format', models.CharField(max_length=100)),
                ('segment_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplatePageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('page_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.PageRevision')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_locations', to='wagtail_i18n_translation_memory.Template')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
