# Generated by Django 2.2.6 on 2019-12-10 17:41

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail_localize.models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("wagtail_localize", "0002_initial_data"),
        ("wagtail_localize_test", "0003_testpage_test_synchronizedfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("is_source_translation", models.BooleanField(default=True)),
                (
                    "locale",
                    models.ForeignKey(
                        default=wagtail_localize.models.default_locale_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtail_localize.Locale",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(
                wagtail_localize.models.TranslatablePageRoutingMixin,
                "wagtailcore.page",
                models.Model,
            ),
        )
    ]
