# Generated by Django 2.2.9 on 2019-12-18 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail_localize.models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize", "0002_initial_data"),
        ("wagtail_localize_test", "0005_create_testhomepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestNonParentalChildObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("is_source_translation", models.BooleanField(default=True)),
                ("field", models.TextField()),
                (
                    "locale",
                    models.ForeignKey(
                        default=wagtail_localize.models.default_locale_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtail_localize.Locale",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_nonparentalchildobjects",
                        to="wagtail_localize_test.TestPage",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
