# Generated by Django 2.2.9 on 2020-01-20 16:56

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail_localize.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0002_initial_data'),
        ('wagtail_localize_test', '0007_more_synchronized_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_source_translation', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('test_charfield', models.CharField(blank=True, max_length=255)),
                ('test_textfield', models.TextField(blank=True)),
                ('test_emailfield', models.EmailField(blank=True, max_length=254)),
                ('locale', models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='InheritedTestModel',
            fields=[
                ('testmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtail_localize_test.TestModel')),
            ],
            bases=('wagtail_localize_test.testmodel',),
        ),
    ]
