# Generated by Django 2.2.9 on 2020-01-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize", "0002_initial_data"),
        ("wagtail_localize_test", "0008_inheritedtestmodel_testmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="testchildobject",
            name="placeholder_locale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtail_localize.Locale",
            ),
        ),
        migrations.AddField(
            model_name="testhomepage",
            name="placeholder_locale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtail_localize.Locale",
            ),
        ),
        migrations.AddField(
            model_name="testnonparentalchildobject",
            name="placeholder_locale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtail_localize.Locale",
            ),
        ),
        migrations.AddField(
            model_name="testpage",
            name="placeholder_locale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtail_localize.Locale",
            ),
        ),
        migrations.AddField(
            model_name="testsnippet",
            name="placeholder_locale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtail_localize.Locale",
            ),
        ),
    ]
