# Generated by Django 3.0.6 on 2020-07-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0006_delete_language_model'),
        ('wagtail_localize_test', '0009_auto_20200524_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testchildobject',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='testchildobject',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='testhomepage',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='testhomepage',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='testnonparentalchildobject',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='testnonparentalchildobject',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='testpage',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='testpage',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='testsnippet',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='testsnippet',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
    ]
