# Generated by Django 4.0.3 on 2022-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wagtail_localize_test",
            "0021_alter_testgeneratetranslatablefieldspage_test_streamfield_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NonTranslatableModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
