# Generated by Django 5.2.17 on 2026-08-20 20:49

import django.db.models.deletion
import wagtail.blocks.field_block
import wagtail.fields

from django.db import migrations, models
from wagtail import VERSION as WAGTAIL_VERSION

import tests.testapp.models


if WAGTAIL_VERSION >= (8, 0):
    import swapper

    swapper.set_app_prefix("wagtailcore", "wagtail")
    PAGE_MODEL_NAME = swapper.get_model_name("wagtailcore", "Page").lower()
else:
    PAGE_MODEL_NAME = "wagtailcore.page"


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageWithCustomEditHandler",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=PAGE_MODEL_NAME,
                    ),
                ),
                ("foo_field", models.TextField()),
                ("bar_field", models.TextField()),
                ("baz_field", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=(PAGE_MODEL_NAME, models.Model),
        ),
        migrations.CreateModel(
            name="TestGenerateTranslatableFieldsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=PAGE_MODEL_NAME,
                    ),
                ),
                ("test_charfield", models.CharField(blank=True, max_length=255)),
                (
                    "test_charfield_with_choices",
                    models.CharField(
                        blank=True, choices=[("a", "A"), ("b", "B")], max_length=255
                    ),
                ),
                ("test_textfield", models.TextField(blank=True)),
                ("test_emailfield", models.EmailField(blank=True, max_length=254)),
                ("test_slugfield", models.SlugField(blank=True)),
                ("test_urlfield", models.URLField(blank=True)),
                ("test_richtextfield", wagtail.fields.RichTextField(blank=True)),
                (
                    "test_streamfield",
                    wagtail.fields.StreamField(
                        [
                            ("test_charblock", 0),
                            ("test_textblock", 1),
                            ("test_emailblock", 2),
                            ("test_urlblock", 3),
                            ("test_richtextblock", 4),
                            ("test_rawhtmlblock", 5),
                            ("test_blockquoteblock", 6),
                            ("test_structblock", 8),
                            ("test_listblock", 9),
                            ("test_listblock_in_structblock", 17),
                            ("test_nestedstreamblock", 21),
                            ("test_streamblock_in_structblock", 23),
                            ("test_customstructblock", 8),
                            ("test_customblockwithoutextractmethod", 24),
                            ("test_pagechooserblock", 13),
                            ("test_pagechooserblock_with_restricted_types", 25),
                            ("test_imagechooserblock", 26),
                            ("test_documentchooserblock", 27),
                            ("test_snippetchooserblock", 28),
                            ("test_nontranslatablesnippetchooserblock", 29),
                            ("test_embedblock", 30),
                            ("test_chooserstructblock", 20),
                            ("test_nestedchooserstructblock", 31),
                            ("test_chooser_in_struct_in_listblock", 34),
                            ("test_image_chooser_in_listblock", 35),
                            ("test_document_chooser_in_listblock", 36),
                            (
                                "test_chooser_in_struct_in_list_in_stream_in_listblock",
                                38,
                            ),
                            ("test_imageblock", 39),
                            ("test_imageblock_in_structblock", 40),
                            ("test_imageblock_in_listblock", 41),
                            ("test_imageblock_in_streamblock", 42),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "text block"},
                            ),
                            2: ("wagtail.blocks.EmailBlock", (), {}),
                            3: ("wagtail.blocks.URLBlock", (), {}),
                            4: ("wagtail.blocks.RichTextBlock", (), {}),
                            5: ("wagtail.blocks.RawHTMLBlock", (), {}),
                            6: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            7: ("wagtail.blocks.TextBlock", (), {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("field_a", 7), ("field_b", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.ListBlock", (7,), {}),
                            10: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            11: (
                                "wagtail.blocks.ListBlock",
                                (wagtail.blocks.field_block.CharBlock,),
                                {},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "label": "List Heading",
                                    "required": False,
                                },
                            ),
                            13: ("wagtail.blocks.PageChooserBlock", (), {}),
                            14: ("wagtail.blocks.ListBlock", (13,), {}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 12), ("pages", 14)]],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 10), ("items", 11), ("links_list", 16)]],
                                {},
                            ),
                            18: ("wagtail.blocks.CharBlock", (), {}),
                            19: ("wagtail.blocks.ListBlock", (18,), {}),
                            20: ("wagtail.blocks.StructBlock", [[("page", 13)]], {}),
                            21: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("block_a", 7),
                                        ("block_b", 7),
                                        ("block_l", 19),
                                        ("chooser", 13),
                                        ("chooser_in_struct", 20),
                                        ("chooser_in_list", 14),
                                    ]
                                ],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.StreamBlock",
                                [[("page", 13), ("checklist", 20)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("nested_stream", 22)]],
                                {},
                            ),
                            24: (
                                "tests.testapp.models.CustomBlockWithoutExtractMethod",
                                (),
                                {},
                            ),
                            25: (
                                "wagtail.blocks.PageChooserBlock",
                                (["testpages.TestHomePage", "testpages.TestPage"],),
                                {},
                            ),
                            26: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            27: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {},
                            ),
                            28: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (tests.testapp.models.TestSnippet,),
                                {},
                            ),
                            29: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (tests.testapp.models.NonTranslatableSnippet,),
                                {},
                            ),
                            30: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [[("nested_page", 20)]],
                                {},
                            ),
                            32: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            33: ("wagtail.blocks.StructBlock", [[("page", 32)]], {}),
                            34: ("wagtail.blocks.ListBlock", (33,), {}),
                            35: ("wagtail.blocks.ListBlock", (26,), {}),
                            36: ("wagtail.blocks.ListBlock", (27,), {}),
                            37: ("wagtail.blocks.StreamBlock", [[("list", 34)]], {}),
                            38: ("wagtail.blocks.ListBlock", (37,), {}),
                            39: ("wagtail.images.blocks.ImageBlock", [], {}),
                            40: (
                                "wagtail.blocks.StructBlock",
                                [[("the_image", 39)]],
                                {},
                            ),
                            41: ("tests.testapp.models.ImageBlockInListBlock", (), {}),
                            42: (
                                "wagtail.blocks.StreamBlock",
                                [[("the_image", 39)]],
                                {},
                            ),
                        },
                    ),
                ),
                ("test_customfield", tests.testapp.models.TestCustomField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(PAGE_MODEL_NAME, models.Model),
        ),
        migrations.CreateModel(
            name="TestHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=PAGE_MODEL_NAME,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(PAGE_MODEL_NAME, models.Model),
        ),
        migrations.CreateModel(
            name="TestPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=PAGE_MODEL_NAME,
                    ),
                ),
                (
                    "test_charfield",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="char field",
                    ),
                ),
                ("test_textfield", models.TextField(blank=True)),
                ("test_emailfield", models.EmailField(blank=True, max_length=254)),
                ("test_slugfield", models.SlugField(blank=True)),
                ("test_urlfield", models.URLField(blank=True)),
                ("test_richtextfield", wagtail.fields.RichTextField(blank=True)),
                (
                    "test_null_richtextfield",
                    wagtail.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "test_streamfield",
                    wagtail.fields.StreamField(
                        [
                            ("test_charblock", 0),
                            ("test_textblock", 1),
                            ("test_emailblock", 2),
                            ("test_urlblock", 3),
                            ("test_richtextblock", 4),
                            ("test_rawhtmlblock", 5),
                            ("test_blockquoteblock", 6),
                            ("test_structblock", 8),
                            ("test_listblock", 9),
                            ("test_listblock_in_structblock", 17),
                            ("test_nestedstreamblock", 21),
                            ("test_streamblock_in_structblock", 23),
                            ("test_customstructblock", 8),
                            ("test_customblockwithoutextractmethod", 24),
                            ("test_pagechooserblock", 13),
                            ("test_pagechooserblock_with_restricted_types", 25),
                            ("test_imagechooserblock", 26),
                            ("test_documentchooserblock", 27),
                            ("test_snippetchooserblock", 28),
                            ("test_nontranslatablesnippetchooserblock", 29),
                            ("test_embedblock", 30),
                            ("test_chooserstructblock", 20),
                            ("test_nestedchooserstructblock", 31),
                            ("test_chooser_in_struct_in_listblock", 34),
                            ("test_image_chooser_in_listblock", 35),
                            ("test_document_chooser_in_listblock", 36),
                            (
                                "test_chooser_in_struct_in_list_in_stream_in_listblock",
                                38,
                            ),
                            ("test_imageblock", 39),
                            ("test_imageblock_in_structblock", 40),
                            ("test_imageblock_in_listblock", 41),
                            ("test_imageblock_in_streamblock", 42),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "text block"},
                            ),
                            2: ("wagtail.blocks.EmailBlock", (), {}),
                            3: ("wagtail.blocks.URLBlock", (), {}),
                            4: ("wagtail.blocks.RichTextBlock", (), {}),
                            5: ("wagtail.blocks.RawHTMLBlock", (), {}),
                            6: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            7: ("wagtail.blocks.TextBlock", (), {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("field_a", 7), ("field_b", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.ListBlock", (7,), {}),
                            10: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            11: (
                                "wagtail.blocks.ListBlock",
                                (wagtail.blocks.field_block.CharBlock,),
                                {},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "label": "List Heading",
                                    "required": False,
                                },
                            ),
                            13: ("wagtail.blocks.PageChooserBlock", (), {}),
                            14: ("wagtail.blocks.ListBlock", (13,), {}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 12), ("pages", 14)]],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 10), ("items", 11), ("links_list", 16)]],
                                {},
                            ),
                            18: ("wagtail.blocks.CharBlock", (), {}),
                            19: ("wagtail.blocks.ListBlock", (18,), {}),
                            20: ("wagtail.blocks.StructBlock", [[("page", 13)]], {}),
                            21: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("block_a", 7),
                                        ("block_b", 7),
                                        ("block_l", 19),
                                        ("chooser", 13),
                                        ("chooser_in_struct", 20),
                                        ("chooser_in_list", 14),
                                    ]
                                ],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.StreamBlock",
                                [[("page", 13), ("checklist", 20)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("nested_stream", 22)]],
                                {},
                            ),
                            24: (
                                "tests.testapp.models.CustomBlockWithoutExtractMethod",
                                (),
                                {},
                            ),
                            25: (
                                "wagtail.blocks.PageChooserBlock",
                                (["testpages.TestHomePage", "testpages.TestPage"],),
                                {},
                            ),
                            26: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            27: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {},
                            ),
                            28: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (tests.testapp.models.TestSnippet,),
                                {},
                            ),
                            29: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (tests.testapp.models.NonTranslatableSnippet,),
                                {},
                            ),
                            30: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [[("nested_page", 20)]],
                                {},
                            ),
                            32: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            33: ("wagtail.blocks.StructBlock", [[("page", 32)]], {}),
                            34: ("wagtail.blocks.ListBlock", (33,), {}),
                            35: ("wagtail.blocks.ListBlock", (26,), {}),
                            36: ("wagtail.blocks.ListBlock", (27,), {}),
                            37: ("wagtail.blocks.StreamBlock", [[("list", 34)]], {}),
                            38: ("wagtail.blocks.ListBlock", (37,), {}),
                            39: ("wagtail.images.blocks.ImageBlock", [], {}),
                            40: (
                                "wagtail.blocks.StructBlock",
                                [[("the_image", 39)]],
                                {},
                            ),
                            41: ("tests.testapp.models.ImageBlockInListBlock", (), {}),
                            42: (
                                "wagtail.blocks.StreamBlock",
                                [[("the_image", 39)]],
                                {},
                            ),
                        },
                    ),
                ),
                ("test_customfield", tests.testapp.models.TestCustomField(blank=True)),
                (
                    "test_synchronized_charfield",
                    models.CharField(blank=True, max_length=255),
                ),
                ("test_synchronized_textfield", models.TextField(blank=True)),
                (
                    "test_not_overridable_synchronized_textfield",
                    models.TextField(blank=True),
                ),
                (
                    "test_synchronized_emailfield",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("test_synchronized_slugfield", models.SlugField(blank=True)),
                ("test_synchronized_urlfield", models.URLField(blank=True)),
                (
                    "test_synchronized_richtextfield",
                    wagtail.fields.RichTextField(blank=True),
                ),
                (
                    "test_synchronized_streamfield",
                    wagtail.fields.StreamField(
                        [
                            ("test_charblock", 0),
                            ("test_textblock", 1),
                            ("test_emailblock", 2),
                            ("test_urlblock", 3),
                            ("test_richtextblock", 4),
                            ("test_rawhtmlblock", 5),
                            ("test_blockquoteblock", 6),
                            ("test_structblock", 8),
                            ("test_listblock", 9),
                            ("test_listblock_in_structblock", 17),
                            ("test_nestedstreamblock", 21),
                            ("test_streamblock_in_structblock", 23),
                            ("test_customstructblock", 8),
                            ("test_customblockwithoutextractmethod", 24),
                            ("test_pagechooserblock", 13),
                            ("test_pagechooserblock_with_restricted_types", 25),
                            ("test_imagechooserblock", 26),
                            ("test_documentchooserblock", 27),
                            ("test_snippetchooserblock", 28),
                            ("test_nontranslatablesnippetchooserblock", 29),
                            ("test_embedblock", 30),
                            ("test_chooserstructblock", 20),
                            ("test_nestedchooserstructblock", 31),
                            ("test_chooser_in_struct_in_listblock", 34),
                            ("test_image_chooser_in_listblock", 35),
                            ("test_document_chooser_in_listblock", 36),
                            (
                                "test_chooser_in_struct_in_list_in_stream_in_listblock",
                                38,
                            ),
                            ("test_imageblock", 39),
                            ("test_imageblock_in_structblock", 40),
                            ("test_imageblock_in_listblock", 41),
                            ("test_imageblock_in_streamblock", 42),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "text block"},
                            ),
                            2: ("wagtail.blocks.EmailBlock", (), {}),
                            3: ("wagtail.blocks.URLBlock", (), {}),
                            4: ("wagtail.blocks.RichTextBlock", (), {}),
                            5: ("wagtail.blocks.RawHTMLBlock", (), {}),
                            6: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            7: ("wagtail.blocks.TextBlock", (), {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("field_a", 7), ("field_b", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.ListBlock", (7,), {}),
                            10: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            11: (
                                "wagtail.blocks.ListBlock",
                                (wagtail.blocks.field_block.CharBlock,),
                                {},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "label": "List Heading",
                                    "required": False,
                                },
                            ),
                            13: ("wagtail.blocks.PageChooserBlock", (), {}),
                            14: ("wagtail.blocks.ListBlock", (13,), {}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 12), ("pages", 14)]],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 10), ("items", 11), ("links_list", 16)]],
                                {},
                            ),
                            18: ("wagtail.blocks.CharBlock", (), {}),
                            19: ("wagtail.blocks.ListBlock", (18,), {}),
                            20: ("wagtail.blocks.StructBlock", [[("page", 13)]], {}),
                            21: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("block_a", 7),
                                        ("block_b", 7),
                                        ("block_l", 19),
                                        ("chooser", 13),
                                        ("chooser_in_struct", 20),
                                        ("chooser_in_list", 14),
                                    ]
                                ],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.StreamBlock",
                                [[("page", 13), ("checklist", 20)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("nested_stream", 22)]],
                                {},
                            ),
                            24: (
                                "tests.testapp.models.CustomBlockWithoutExtractMethod",
                                (),
                                {},
                            ),
                            25: (
                                "wagtail.blocks.PageChooserBlock",
                                (["testpages.TestHomePage", "testpages.TestPage"],),
                                {},
                            ),
                            26: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            27: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {},
                            ),
                            28: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (tests.testapp.models.TestSnippet,),
                                {},
                            ),
                            29: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (tests.testapp.models.NonTranslatableSnippet,),
                                {},
                            ),
                            30: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [[("nested_page", 20)]],
                                {},
                            ),
                            32: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            33: ("wagtail.blocks.StructBlock", [[("page", 32)]], {}),
                            34: ("wagtail.blocks.ListBlock", (33,), {}),
                            35: ("wagtail.blocks.ListBlock", (26,), {}),
                            36: ("wagtail.blocks.ListBlock", (27,), {}),
                            37: ("wagtail.blocks.StreamBlock", [[("list", 34)]], {}),
                            38: ("wagtail.blocks.ListBlock", (37,), {}),
                            39: ("wagtail.images.blocks.ImageBlock", [], {}),
                            40: (
                                "wagtail.blocks.StructBlock",
                                [[("the_image", 39)]],
                                {},
                            ),
                            41: ("tests.testapp.models.ImageBlockInListBlock", (), {}),
                            42: (
                                "wagtail.blocks.StreamBlock",
                                [[("the_image", 39)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "test_synchronized_customfield",
                    tests.testapp.models.TestCustomField(blank=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(PAGE_MODEL_NAME, models.Model),
        ),
        migrations.CreateModel(
            name="TestWithTranslationModeDisabledPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=PAGE_MODEL_NAME,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(PAGE_MODEL_NAME, models.Model),
        ),
        migrations.CreateModel(
            name="TestWithTranslationModeEnabledPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=PAGE_MODEL_NAME,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(PAGE_MODEL_NAME, models.Model),
        ),
        migrations.CreateModel(
            name="TestOverrideTranslatableFieldsPage",
            fields=[
                (
                    "testgeneratetranslatablefieldspage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="testpages.testgeneratetranslatablefieldspage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("testpages.testgeneratetranslatablefieldspage", models.Model),
        ),
    ]
