# Generated by Django 5.2.17 on 2026-08-20 20:49

import django.db.models.deletion

from django.db import migrations, models
from wagtail import VERSION as WAGTAIL_VERSION


if WAGTAIL_VERSION >= (8, 0):
    import swapper

    swapper.set_app_prefix("wagtailcore", "wagtail")
    PAGE_MODEL_NAME = swapper.get_model_name("wagtailcore", "Page").lower()
else:
    PAGE_MODEL_NAME = "wagtailcore.page"


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("testpages", "0001_initial"),
        ("wagtail_localize_test", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="testgeneratetranslatablefieldspage",
            name="test_nontranslatablesnippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtail_localize_test.nontranslatablesnippet",
            ),
        ),
        migrations.AddField(
            model_name="testgeneratetranslatablefieldspage",
            name="test_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtail_localize_test.testsnippet",
            ),
        ),
        migrations.AddField(
            model_name="testpage",
            name="test_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=PAGE_MODEL_NAME,
            ),
        ),
        migrations.AddField(
            model_name="testpage",
            name="test_page_specific_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="testpages.testhomepage",
            ),
        ),
        migrations.AddField(
            model_name="testpage",
            name="test_page_with_restricted_types",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=PAGE_MODEL_NAME,
            ),
        ),
        migrations.AddField(
            model_name="testpage",
            name="test_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtail_localize_test.testsnippet",
            ),
        ),
        migrations.AddField(
            model_name="testpage",
            name="test_synchronized_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
            ),
        ),
        migrations.AddField(
            model_name="testpage",
            name="test_synchronized_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="testpage",
            name="test_synchronized_snippet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtail_localize_test.testsnippet",
            ),
        ),
    ]
