# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtail_localize_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequestpage',
            name='completed_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.PageRevision'),
        ),
        migrations.AddField(
            model_name='translationrequestpage',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
